name: Convert SVG to PNG and Publish Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
        default: 'v1.0.0'

jobs:
  convert:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y librsvg2-bin zip

    - name: Convert SVG to PNG (32x32, 64x64, 128x128)
      run: |
        mkdir -p out/32x32 out/64x64 out/128x128 out/svg
        jq -cr '.[] | .name' src/assets/@emojis.json | while read emoji;
        do
          rsvg-convert -w 32 -h 32 "public/images/$emoji.svg" -o "out/32x32/${emoji}.png"
          rsvg-convert -w 64 -h 64 "public/images/$emoji.svg" -o "out/64x64/${emoji}.png"
          rsvg-convert -w 128 -h 128 "public/images/$emoji.svg" -o "out/128x128/${emoji}.png"
          cp "public/images/$emoji.svg" "out/svg/$emoji.svg"
        done

    - name: Create zip files of converted images
      run: |
        zip -rj cat_plead_emojis@32.zip out/32x32
        zip -rj cat_plead_emojis@64.zip out/64x64
        zip -rj cat_plead_emojis@128.zip out/128x128
        zip -rj cat_plead_emojis.zip out/svg

    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.release_version }}
        name: Release ${{ github.event.inputs.release_version }}
        draft: false
        prerelease: false
        files: |
          cat_plead_emojis@32.zip
          cat_plead_emojis@64.zip
          cat_plead_emojis@128.zip
          cat_plead_emojis.zip

    - name: Cleanup
      run: rm -rf converted cat_plead_emojis*.zip
